#!/bin/bash
set -e

which python
conda info
conda env list


echo "## Installing PowerShell notebook support. ##"

# dotnet tool install -g PowerShell
# dotnet tool install -g Microsoft.dotnet-interactive
# dotnet interactive jupyter install
