#!/bin/bash
set -e

conda activate notebook

echo "## Installing PowerShell notebook support. ##"

dotnet tool install -g PowerShell
dotnet tool install -g Microsoft.dotnet-interactive
dotnet interactive jupyter install
